export const AGGREGATION_TREE_HEIGHT = 6;
export const TRANSFER_TREE_HEIGHT = 40;
export const GLOBAL_TRANSFER_TREE_HEIGHT = TRANSFER_TREE_HEIGHT + AGGREGATION_TREE_HEIGHT;
export const NUM_BATCH_INVOICES = 10;
