[package]
name = "zerc20-relay"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
client-common = { path = "../client-common", package = "zerc20-client-common" }
actix-web = { workspace = true }
actix-cors = { workspace = true }
alloy = { workspace = true }
anyhow = { workspace = true }
dotenvy = { workspace = true }
env_logger = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
