[package]
name = "zerc20-trusted-setup-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-groth16 = { workspace = true }
ark-grumpkin = { workspace = true }
ark-crypto-primitives = { workspace = true }
ark-poly-commit = { version = "0.5.0", default-features = false }
ark-serialize = { workspace = true }
ark-std = { workspace = true }
arkworks-phase2 = { workspace = true }
backoff = { version = "0.4", features = ["tokio"] }
bytes = "1"
clap = { workspace = true, features = ["derive", "env"] }
ctrlc = { version = "3.4", features = ["termination"] }
dotenvy = { workspace = true }
env_logger = { workspace = true }
folding-schemes = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
indicatif = "0.17"
log = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = [
    "fs",
    "io-util",
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
    "signal",
] }
url = { workspace = true }
uuid = { workspace = true }
zkp = { path = "../../zkp", package = "zerc20-zkp" }
trusted-setup-common = { path = "../common", package = "zerc20-trusted-setup-common" }
alloy = { workspace = true, features = ["signer-local"] }

[features]
default = ["parallel"]
parallel = ["arkworks-phase2/parallel", "trusted-setup-common/parallel"]
