on:
  push:
    branches: ["dev", "main", "master"]
  pull_request:
    branches: ["dev", "main", "master"]

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  format-check:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: cargo fmt
        run: cargo fmt --check --all

  doc:
    name: doc
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Check docs
        run: cargo doc --no-deps --workspace

  typos:
    name: typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: typos-action
        uses: crate-ci/typos@master

  clippy:
    name: clippy
    needs: format-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: r7kamura/rust-problem-matchers@v1
      - name: cargo clippy
        run: cargo clippy --workspace --tests -- -D warnings -D "clippy::perf" -D "clippy::correctness"

  tests:
    name: tests
    needs: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install solc
        run: |
          pip3 install solc-select
          solc-select install 0.8.33
          solc-select use 0.8.33
      - uses: r7kamura/rust-problem-matchers@v1
      - name: Run tests
        run: cargo nextest run --profile ci --workspace
